#!/usr/bin/env python3
"""
export-skill: converts a canonical SKILL.md into other AI runtimes' formats.

This is the mechanism behind the repo's "author once, run anywhere" rule
(.claude/rules/portability.md): one canonical SKILL.md per skill, exports
GENERATED (never hand-maintained) per target runtime.

Targets:
  native     Plain SKILL.md with {{SKILL_DIR}} resolved to a concrete path.
             Works as-is for Snowflake CoCo/Cortex Agents and Databricks
             Genie Code, which implement the same open Agent Skills
             standard (hosting/install differs per platform; content
             doesn't).
  cursor     A Cursor rules file (.mdc): Cursor's frontmatter (description,
             alwaysApply: false -- agent-requested rule), same vendor-
             neutral body, {{SKILL_DIR}} resolved.
  agents-md  A section suitable for merging into an AGENTS.md (OpenAI
             Codex CLI convention): H2-headed, frontmatter folded into
             prose, {{SKILL_DIR}} resolved.

{{SKILL_DIR}} resolution: exports reference helper scripts by a path
relative to the REPO ROOT (.claude/skills/<name>) by default, overridable
with --skill-dir-value for runtimes where the skill folder lives elsewhere
(e.g. uploaded to a Snowflake stage).

Usage:
    python tools/export-skill/export_skill.py --skill <name> --target native|cursor|agents-md
        [--out-dir exports/] [--skill-dir-value <path>]
    python tools/export-skill/export_skill.py --all --target cursor [--out-dir exports/]

No dependencies beyond the Python standard library.
"""
import argparse
import glob
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SKILLS_DIR = os.path.join(REPO_ROOT, ".claude", "skills")


def parse_skill_md(path):
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing frontmatter")
    fm = {}
    body_start = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            body_start = i + 1
            break
        if ":" in line:
            key, _, value = line.partition(":")
            fm[key.strip()] = value.strip()
    if body_start is None:
        raise ValueError(f"{path}: unterminated frontmatter")
    body = "\n".join(lines[body_start:]).strip("\n")
    return fm, body


def resolve_skill_dir(body, skill_name, skill_dir_value):
    value = skill_dir_value or f".claude/skills/{skill_name}"
    return body.replace("{{SKILL_DIR}}", value)


def export_native(fm, body, skill_name, skill_dir_value):
    header = "---\n" + "\n".join(f"{k}: {v}" for k, v in fm.items()) + "\n---\n\n"
    note = (f"<!-- GENERATED by tools/export-skill from "
            f".claude/skills/{skill_name}/SKILL.md -- do not edit by hand -->\n\n")
    return note + header + resolve_skill_dir(body, skill_name, skill_dir_value) + "\n", f"{skill_name}/SKILL.md"


def export_cursor(fm, body, skill_name, skill_dir_value):
    front = (
        "---\n"
        f"description: {fm.get('description', '')}\n"
        "alwaysApply: false\n"
        "---\n\n"
    )
    note = (f"<!-- GENERATED by tools/export-skill from "
            f".claude/skills/{skill_name}/SKILL.md -- do not edit by hand -->\n\n")
    meta = (f"> Skill: `{fm.get('name', skill_name)}` | risk: {fm.get('risk', '?')} | "
            f"loop-tier: {fm.get('loop-tier', '?')}\n\n")
    return front + note + meta + resolve_skill_dir(body, skill_name, skill_dir_value) + "\n", f"{skill_name}.mdc"


def export_agents_md(fm, body, skill_name, skill_dir_value):
    note = (f"<!-- GENERATED by tools/export-skill from "
            f".claude/skills/{skill_name}/SKILL.md -- do not edit by hand -->\n")
    section = (
        f"## Skill: {fm.get('name', skill_name)}\n\n"
        f"{note}\n"
        f"{fm.get('description', '')}\n\n"
        f"(risk: {fm.get('risk', '?')}, loop-tier: {fm.get('loop-tier', '?')})\n\n"
    )
    # Demote the body's H2s to H3s so the merged AGENTS.md keeps a sane outline.
    demoted = "\n".join(("#" + line if line.startswith("## ") else line) for line in
                        resolve_skill_dir(body, skill_name, skill_dir_value).splitlines())
    return section + demoted + "\n", f"{skill_name}.agents.md"


EXPORTERS = {"native": export_native, "cursor": export_cursor, "agents-md": export_agents_md}


def export_one(skill_name, target, out_dir, skill_dir_value):
    src = os.path.join(SKILLS_DIR, skill_name, "SKILL.md")
    if not os.path.isfile(src):
        raise FileNotFoundError(f"no such skill: {skill_name} (looked for {src})")
    fm, body = parse_skill_md(src)
    content, rel_out = EXPORTERS[target](fm, body, skill_name, skill_dir_value)
    out_path = os.path.join(out_dir, target, rel_out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    return out_path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", help="Skill folder name under .claude/skills/")
    parser.add_argument("--all", action="store_true", help="Export every skill")
    parser.add_argument("--target", required=True, choices=sorted(EXPORTERS))
    parser.add_argument("--out-dir", default=os.path.join(REPO_ROOT, "exports"))
    parser.add_argument("--skill-dir-value", default=None,
                        help="What {{SKILL_DIR}} resolves to (default: .claude/skills/<name>)")
    args = parser.parse_args()

    if not args.skill and not args.all:
        parser.error("give --skill <name> or --all")

    if args.all:
        names = sorted(os.path.basename(os.path.dirname(p))
                       for p in glob.glob(os.path.join(SKILLS_DIR, "*", "SKILL.md")))
    else:
        names = [args.skill]

    for name in names:
        out = export_one(name, args.target, args.out_dir, args.skill_dir_value)
        print(f"exported: {os.path.relpath(out, REPO_ROOT)}")


if __name__ == "__main__":
    main()
